# Generated by Django 4.1.1 on 2022-10-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('tahun', models.FloatField()),
            ],
            options={
                'verbose_name': 'Polling',
                'verbose_name_plural': 'Pollings',
            },
        ),
    ]
