# Generated by Django 4.1.1 on 2022-10-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polling',
            options={},
        ),
    ]
