# Generated by Django 4.1.1 on 2022-10-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_polling_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling',
            name='tahun',
            field=models.IntegerField(),
        ),
    ]
